# yamllint disable-line rule:document-start
name: ci-mu-plugin

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      PHP_VERSION:
        type: number
        default: 7.4
        required: false
    secrets:
      PRIVATE_PACKAGIST_TOKEN:
        required: true

jobs:
  php:
    name: php-style-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ inputs.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "${GITHUB_OUTPUT}"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-${{ inputs.PHP_VERSION }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ inputs.PHP_VERSION }}-composer-

      - name: Setup Composer Private Packagist authentication
        # yamllint disable-line rule:line-length
        run: composer config --global --auth http-basic.repo.packagist.com itineris ${{ secrets.PRIVATE_PACKAGIST_TOKEN }}

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - run: composer run-script style:check
