# yamllint disable-line rule:document-start
name: "Labeler"

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
  schedule:
    - cron: "0 7 * * 1,2,3,4,5"

jobs:
  triage:
    # yamllint disable-line rule:line-length
    if: ${{ github.actor == 'kodiakhq[bot]' || github.actor == 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
