# yamllint disable-line rule:document-start
name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - development
  schedule:
    - cron: "0 10 * * 1,2,3,4,5"

jobs:
  deploy:
    uses: Feel-Created-Ltd/.github/.github/workflows/trellis-deploy-development.yml@main
    with:
      NODE_VERSION: 12
      THEME_NAME: chiuni
      TRELLIS_ENVIRONMENT: "dev-remote"
      TRELLIS_REPOSITORY: Feel-Created-Ltd/www.chi.ac.uk-trellis
    secrets:
      REPO_PAT: ${{ secrets.REPO_PAT }}
      TRELLIS_DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
      TRELLIS_DEPLOY_SSH_KNOWN_HOSTS: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
      TRELLIS_BEDROCK_SSH_PRIVATE_KEY: ${{ secrets.TRELLIS_BEDROCK_SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      ITINERIS_NPM_AUTH_TOKEN: ${{ secrets.ITINERIS_NPM_AUTH_TOKEN }}
      ZEROTIER_CENTRAL_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      ZEROTIER_GATEWAY_IP: ${{ secrets.ZEROTIER_GATEWAY_IP }}
      ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}

  check_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Trellis
        uses: actions/checkout@v4
        with:
          repository: Feel-Created-Ltd/www.chi.ac.uk-trellis
          ref: development
          path: trellis
          token: ${{ secrets.REPO_PAT }}

      - name: Check hosts/dev-remote for correct IP
        run: |
          EXPECTED_IP="35.246.17.50"
          ACTUAL_IP=$(grep -Eo 'ansible_host=[0-9]{1,3}(\.[0-9]{1,3}){3}' trellis/hosts/dev-remote | sed 's/ansible_host=//g')
          if [ "$ACTUAL_IP" != "$EXPECTED_IP" ]; then
            echo "Error: IP in hosts/dev-remote ($ACTUAL_IP) does not match expected ($EXPECTED_IP)"
            exit 1
          fi
          echo "IP address in hosts/dev-remote is correct: $ACTUAL_IP"

      - name: Setup Bedrock SSH key
        if: ${{ secrets.TRELLIS_BEDROCK_SSH_PRIVATE_KEY != '' }}
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.TRELLIS_BEDROCK_SSH_PRIVATE_KEY }}
